### ISSUE TITLE
Request Video player code

### ISSUE THREAD

**Issue by ghost** [stbsdk/demo#1]
How do we call the video player and what parameters we pass and how we pass the video URL?

I.e for adding a button we add this 

```
new Button({
	value: 'show heavy image',
	}),
```

**Comment by DarkPark** [comment]
https://stbapi.github.io/

**Comment by ghost** [comment]
This doesn't answer the question, how we call the player. "https://stbapi.github.io/"

if stbapi is everything then why use stbsdk?

**Comment by DarkPark** [comment]
you don't have to use stbsdk

**Comment by ghost** [comment]
I have spent 3 days on the code and i am stuck at this
```
panel.add(
	new Panel({
		$node: document.getElementById('pageMainTabPlayerSimple'),
		children: [
			new Player({
				uri: '',
       			        solution: 'auto'
			}),
		]
	})
);
```

The player is not showing on stb.

**Comment by DarkPark** [comment]
this repo is outdated and not maintained
the most relevant repo - https://github.com/stbsdk/boilerplate/tree/develop
but seems to me you shouldn't start with any frameworks
just use direct gSTB API calls
all examples are available in https://stbapi.github.io/
